[package]
name = "easy_microservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-trait = "0.1.60"
anyhow = "1.0.68"
tokio = { version = "1.23.0", features = ["full"] }